<!DOCTYPE html>
<html>
<head>
   <title>Belajar Menggunakan git</title>
</head>
<body>
<h1>Latihan Menggunakan PHP</h1>
<form action="#" method="post">
<p>
   <label for="nama">Nama : </label>
   <input type="text" name="nama" id="nama" required autocomplete maxlength="50">
</p>
<p>
   <label for="jenis kelamin">jenis kelamin : </label>
   <select name="jenis kelamin" id="jenis kelamin" required>
     <option value="">--jenis kelamin--</option>
     <option value="PRIA">PRIA</option>
     <option value="WANITA">WANITA</option>
   </select>
</p>
<p>
   <input type="submit" value="Kirim">
   <input type="reset" value="Reset">
</p>
</form>
</body>
</html>
